# Generated by Django 4.1 on 2022-08-12 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_clouduser_birth_date_clouduser_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clouduser',
            old_name='birth_date',
            new_name='user_birthdate',
        ),
        migrations.RemoveField(
            model_name='clouduser',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='clouduser',
            name='email',
        ),
        migrations.RemoveField(
            model_name='clouduser',
            name='name',
        ),
        migrations.RemoveField(
            model_name='clouduser',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='clouduser',
            name='user_email',
            field=models.EmailField(blank=True, max_length=128, null=True, unique=True, verbose_name='E-mail'),
        ),
        migrations.AddField(
            model_name='clouduser',
            name='user_id',
            field=models.CharField(max_length=32, null=True, unique=True, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='clouduser',
            name='user_name',
            field=models.CharField(max_length=16, null=True, verbose_name='NAME'),
        ),
        migrations.AddField(
            model_name='clouduser',
            name='user_pw',
            field=models.CharField(max_length=128, null=True, verbose_name='PW'),
        ),
    ]
